{% set name = "kr8s" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kr8s-{{ version }}.tar.gz
  sha256: 00a1517bfe3b05d9c245885f08961d17e2fbd816c2e31f5ff910d5f3788393c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - anyio >=3.7.0
    - asyncache >=0.3.1
    - cryptography >=35
    - exceptiongroup >=1.2.0
    - httpx >=0.24.1
    - httpx-ws >=0.5.2
    - python-box >=7.0.1
    - python-jsonpath >=0.7.1
    - pyyaml >=6.0

test:
  imports:
    - kr8s
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kr8s.org
  summary: A Kubernetes API library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
