{% set name = "kr8s" %}
{% set version = "0.20.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kr8s-{{ version }}.tar.gz
  sha256: f181a2a51f8ddac3f8883db67d046a1bc74bcdbf19655cfaaf345a316fb916e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - cachetools >=5.2.0
    - packaging >=23.0
    - typing_extensions >=4.12.2
    - python >={{ python_min }}
    - anyio >=3.7.0
    - asyncache >=0.3.1
    - cryptography >=35
    - exceptiongroup >=1.2.0
    - httpx >=0.24.1
    - httpx-ws >=0.7.0
    - python-box >=7.0.1
    - python-jsonpath >=0.7.1
    - pyyaml >=6.0

test:
  imports:
    - kr8s
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://kr8s.org
  summary: A Kubernetes API library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
