{% set name = "kr8s" %}
{% set version = "0.8.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kr8s-{{ version }}.tar.gz
  sha256: 3f5444f0ffad2bdd3faeaa68f9bc8653a60701d0af7bdd213ed06e6851f3bec0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.8.4
    - pyyaml >=6.0
    - python-jsonpath >=0.7.1
    - anyio >=3.7.0
    - httpx >=0.24.1
    - python-box >=7.0.1

test:
  imports:
    - kr8s
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kr8s.org
  summary: A Kubernetes API library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
