{% set name = "kr8s" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kr8s-{{ version }}.tar.gz
  sha256: a08f11751587b16f572fac0d2d79cffed55e8957513f7812797b164cd70c6e63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.8.4
    - pyyaml >=6.0
    - python-jsonpath >=0.7.1
    - anyio >=3.7.0
    - httpx >=0.24.1
    - python-box >=7.0.1

test:
  imports:
    - kr8s
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kr8s.org
  summary: A Kubernetes API library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
