{% set name = "kr8s" %}
{% set version = "0.8.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kr8s-{{ version }}.tar.gz
  sha256: 708c77e480e754aadfdf366609ce89d6e8100085a15980f4f77fca8066f19397

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0,<4.0.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - aiohttp
    - pyyaml >=6.0.0,<7.0.0
    - python-jsonpath >=0.7.1,<0.8.0
    - anyio >=3.7.0,<4.0.0
    - httpx >=0.24.1,<0.25.0
    - sniffio >=1.1
    - python-box >=7.0.1,<8.0.0

test:
  imports:
    - kr8s
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://kr8s.org
  summary: A Kubernetes API library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobtomlinson
